# Generated by Django 3.0.5 on 2020-05-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
    ]
