# Generated by Django 3.0.5 on 2020-05-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20200502_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='image',
        ),
        migrations.AddField(
            model_name='solution',
            name='solution_file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
