# Generated by Django 3.0.5 on 2020-05-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200502_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='solution_file',
        ),
        migrations.AddField(
            model_name='solution',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
